spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: ddubok-test
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: false
    hibernate:
      ddl-auto: create-drop
      format_sql: true
  data:
    redis:
      host: localhost
      port: 6379
  social:
    kakao-id: ${KAKAO_ID}
    naver-id: ${NAVER_ID}
    naver-secret: ${NAVER_SECRET}
    meta-id: ${META_ID}
    meta-secret: ${META_SECRET}
    google-id: ${GOOGLE_ID}
    google-secret: ${GOOGLE_SECRET}
  jwt:
    secret: ${JWT_SECRET}
    expiration: ${ACCESS_EXPIRATION}
    refresh-token:
      expiration: ${REFRESH_EXPIRATION}
    redirect-url: ${JWT_REDIRECT_URL}

springdoc:
  swagger-ui:
    path: /api/swagger-ui.html

cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET_NAME}
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

openai:
  api:
    key: ${OPEN_AI_KEY}
    url: ${OPEN_AI_URL}
  model: ${OPEN_AI_MODEL}
