spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: ddubok
  datasource:
    url: jdbc:mariadb://localhost:3306/ddubok?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
    show-sql: false
    hibernate:
      ddl-auto: none
      format_sql: true
  data:
    redis:
      host: redis
      port: 6379

springdoc:
  swagger-ui:
    path: /api/swagger-ui.html