spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: ddubok
  datasource:
    url: jdbc:mariadb://localhost:3306/ddubok?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: org.mariadb.jdbc.Driver
    username: ddubok
    password: ddubok123!
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
    show-sql: false
    hibernate:
      ddl-auto: update
      format_sql: true
  data:
    redis:
      host: localhost
      port: 6379

#swagger : account ?? ???? ??
springdoc:
  swagger-ui:
    path: /api/swagger-ui.html