spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: ddubok
  datasource:
    url: jdbc:mariadb://localhost:3306/ddubok?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: org.mariadb.jdbc.Driver
    username: ddubok
    password: ddubok123!
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
    show-sql: false
    hibernate:
      ddl-auto: update
      format_sql: true
  data:
    redis:
      host: localhost
      port: 6379
  social:
    kakao-id: ${KAKAO_ID}
    naver-id: ${NAVER_ID}
    naver-secret: ${NAVER_SECRET}
    x-id: ${X_ID}
    x-secret: ${X_SECRET}
    google-id: ${GOOGLE_ID}
    google-secret: ${GOOGLE_SECRET}
    domain-url: ${DOMAIN_URL}
  jwt:
    secret: ${JWT_SECRET}
    expiration: ${ACCESS_EXPIRATION}
    refresh-token:
      expiration: ${REFRESH_EXPIRATION}
    redirect-url: ${JWT_REDIRECT_URL}

springdoc:
  swagger-ui:
    path: /api/swagger-ui.html

cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET_NAME}
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

openai:
  api:
    key: ${OPEN_AI_KEY}
    url: ${OPEN_AI_URL}
  model: ${OPEN_AI_MODEL}

firebase:
  config:
    path: firebase/ddubokFirebase.json